language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
    - pip install coveralls

script:
    - nosetests --with-coverage --cover-tests --cover-package=pyx12 --cover-erase

after_success:
    - coveralls
